apiVersion: v1
kind: Secret
metadata:
  name: genai-stack-secrets
type: Opaque
stringData:
  supabase_anon_key: "your-supabase-anon-key"
  database_url: "postgresql://user:password@host:5432/database"
  openai_api_key: "your-openai-api-key"
  serpapi_key: "your-serpapi-key"
